Suppressed assumed Psalm bug regarding exception handlers.
See https://github.com/SidRoberts/centum/runs/3990816824?check_suite_focus=true

```
ERROR: DocblockTypeContradiction - src/Console/Application.php:116:21 - Operand of type false is always false (see https://psalm.dev/155)
                if (is_a($exception, $exceptionClass)) {

ERROR: DocblockTypeContradiction - src/Router/Router.php:92:21 - Operand of type false is always false (see https://psalm.dev/155)
                if (is_a($exception, $exceptionClass)) {
```